# Generated by Django 5.2.4 on 2025-08-26 08:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='turfuser',
            options={'verbose_name': 'Turf User', 'verbose_name_plural': 'Turf Users'},
        ),
        migrations.AlterModelOptions(
            name='turfvenue',
            options={'ordering': ['name'], 'verbose_name': 'Turf Venue', 'verbose_name_plural': 'Turf Venues'},
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 26, 8, 31, 27, 610241, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turfvenue',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_turfs', to=settings.AUTH_USER_MODEL),
        ),
    ]
