# Generated by Django 5.2.4 on 2025-08-05 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0002_alter_turf_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Other_Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('sports_type', models.CharField(max_length=50)),
                ('price_per_hour', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='turf_images/')),
                ('no_of_players', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_turfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
