# Generated by Django 5.2.4 on 2025-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
