# Generated by Django 5.2.4 on 2025-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome class, e.g., 'fas fa-parking'", max_length=50, null=True)),
            ],
        ),
    ]
