# Generated by Django 5.2.4 on 2025-09-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0007_amenity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='name',
            new_name='amen_name',
        ),
    ]
