# Generated by Django 5.2.4 on 2025-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurfApp', '0008_rename_name_amenity_amen_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name_plural': 'Amenities'},
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='amen_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='turfvenue',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='TurfApp.amenity'),
        ),
        migrations.AddField(
            model_name='turfvenue',
            name='custom_amenities',
            field=models.CharField(blank=True, help_text="Enter comma-separated custom amenities, e.g., 'Free WiFi, Scoreboard'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='turfvenue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turfvenue',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
